# Generated by Django 5.2.15 on 2026-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino')], max_length=20)),
                ('weight_kg', models.FloatField(help_text='Weight in kilograms')),
                ('height_cm', models.FloatField(help_text='Height in centimeters')),
                ('heart_rate', models.FloatField(help_text='Beats per minute')),
                ('oxygen_saturation', models.FloatField(help_text='Arterial O2 saturation (%)')),
                ('age_months', models.FloatField(help_text='Age at first visit, in months')),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('primary_symptom', models.CharField(max_length=100)),
                ('secondary_symptoms', models.CharField(max_length=100)),
                ('murmur_type', models.CharField(max_length=50)),
                ('murmur_grade', models.CharField(max_length=20)),
                ('murmur_zone', models.CharField(max_length=150)),
                ('predicted_class', models.CharField(choices=[('VSD', 'VSD (Ventricular Septal Defect)'), ('ASD', 'ASD (Atrial Septal Defect)'), ('PDA', 'PDA (Patent Ductus Arteriosus)')], max_length=10)),
                ('probability_asd', models.FloatField(default=0.0)),
                ('probability_pda', models.FloatField(default=0.0)),
                ('probability_vsd', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(help_text='Probability of the predicted class (0-1)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
