"""
Inference layer for the trained Logistic Regression CHD classifier.

This module reproduces — for a single form submission — the exact same
preprocessing/encoding steps that were applied to the full training set in
`Copy_of_Final_CHD_Classification.ipynb` (see /training/train_lr.py for the
script that produced the artifacts loaded here). Keeping the two in lockstep
is what makes the Django prediction correct: the model was fit on a specific
column layout (order, one-hot categories, ordinal mapping, scaling) and will
silently produce garbage if that layout isn't reproduced exactly.
"""
import json
import threading

import joblib
import numpy as np
import pandas as pd
from django.conf import settings

_lock = threading.RLock()  # RLock: _load_all() calls get_config() while already
                            # holding the lock, so it must be re-entrant.
_cache = {}


def _artifacts_dir():
    return settings.ML_ARTIFACTS_DIR


def get_config():
    """Lightweight: just the JSON encoding config (used by forms.py to build
    dropdown choices without loading the heavier model/scaler pickles)."""
    if 'config' not in _cache:
        with _lock:
            if 'config' not in _cache:
                with open(_artifacts_dir() / 'encoding_config.json') as f:
                    _cache['config'] = json.load(f)
    return _cache['config']


def _load_all():
    if 'model' not in _cache:
        with _lock:
            if 'model' not in _cache:
                d = _artifacts_dir()
                _cache['model'] = joblib.load(d / 'lr_model.joblib')
                _cache['scaler'] = joblib.load(d / 'scaler.joblib')
                _cache['label_encoder'] = joblib.load(d / 'label_encoder.joblib')
                _cache['config'] = get_config()
    return _cache


def _one_hot_group(value, categories, prefix):
    """Reproduces `topn_ohe` from the notebook for a single value: one column
    per known training category, plus an `_Other` bucket for anything else."""
    row = {f'{prefix}_{c}': 0 for c in categories}
    row[f'{prefix}_Other'] = 0
    if value in categories:
        row[f'{prefix}_{value}'] = 1
    else:
        row[f'{prefix}_Other'] = 1
    return row


def _encode_single(raw: dict, config: dict) -> pd.DataFrame:
    row = {
        'Gender': config['gender_map'].get(raw['Gender'], 0),
        'Weight (KG)': float(raw['Weight (KG)']),
        'Height (CM)': float(raw['Height (CM)']),
        'Heart Rate': float(raw['Heart Rate']),
        'Arterial Oxygen Saturation': float(raw['Arterial Oxygen Saturation']),
        'Age at First Visit (months)': float(raw['Age at First Visit (months)']),
        'Systolic BP': float(raw['Systolic BP']),
        'Diastolic BP': float(raw['Diastolic BP']),
        'Murmur Grade': config['grade_map'].get(raw['Murmur Grade'], 0),
    }
    row.update(_one_hot_group(raw['Primary Symptom'], config['primary_symptom_categories'], 'PrimarySx'))
    row.update(_one_hot_group(raw['Secondary Symptoms'], config['secondary_symptom_categories'], 'SecondarySx'))
    row.update(_one_hot_group(raw['Murmur Type'], config['murmur_type_categories'], 'MurmurType'))
    row.update(_one_hot_group(raw['Murmur Zone'], config['murmur_zone_categories'], 'MurmurZone'))

    df = pd.DataFrame([row])
    # Reindex guarantees the exact column order (and set) the scaler/model
    # were fit on, regardless of dict insertion order above.
    df = df.reindex(columns=config['feature_order'], fill_value=0)
    return df


_RECOMMENDATIONS = {
    'VSD': (
        "The model's top prediction is Ventricular Septal Defect (VSD) — a hole in the "
        "wall separating the heart's lower chambers. Many small VSDs close on their own, "
        "while larger ones may require monitoring or surgical closure."
    ),
    'ASD': (
        "The model's top prediction is Atrial Septal Defect (ASD) — a hole in the wall "
        "separating the heart's upper chambers. ASDs are often well tolerated in early "
        "childhood but should be followed to decide whether closure is needed."
    ),
    'PDA': (
        "The model's top prediction is Patent Ductus Arteriosus (PDA) — a persistent "
        "connection between two major vessels that normally closes shortly after birth. "
        "Treatment ranges from watchful waiting to medication or closure procedures."
    ),
}

def build_recommendation(predicted_class: str) -> str:
    base = _RECOMMENDATIONS.get(predicted_class, "")
    disclaimer = (
        "This result is generated by a research/educational machine-learning model and "
        "is not a medical diagnosis. Always consult a qualified pediatric cardiologist."
    )
    return f"{base} {disclaimer}"


def predict_chd(raw: dict) -> dict:
    """
    raw: dict with keys matching the cleaned feature names used in training:
        Gender, Weight (KG), Height (CM), Heart Rate, Arterial Oxygen Saturation,
        Age at First Visit (months), Systolic BP, Diastolic BP,
        Primary Symptom, Secondary Symptoms, Murmur Type, Murmur Grade, Murmur Zone
    """
    state = _load_all()
    config = state['config']

    X = _encode_single(raw, config)
    X_scaled = state['scaler'].transform(X)
    proba = state['model'].predict_proba(X_scaled)[0]
    classes = list(state['label_encoder'].classes_)  # ['ASD', 'PDA', 'VSD']

    proba_map = {cls: float(p) for cls, p in zip(classes, proba)}
    pred_idx = int(np.argmax(proba))
    predicted_class = classes[pred_idx]
    confidence = float(proba[pred_idx])

    recommendation = build_recommendation(predicted_class)

    return {
        'predicted_class': predicted_class,
        'confidence': confidence,
        'probabilities': proba_map,
        'recommendation': recommendation,
    }
